### ISSUE TITLE
Role prendre soin : le sortir des roles strucurels

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/constitution-cellular-governance#101]
Il y a une proposition pour sortir le role prendre soin des roles structurels et l'intégrer dans les éléments optionnels qui est sortie lors de la réunion chapitrage ouverte du 21 avril 2023. 

L'argument est qu'après expérimentation, les clients accompagnés ne le mettent pas en place, et que même l'équipe gouvernance cellulaire ne l'a pas mis en place. 

Merci de mettre pouce levé si vous etes fan, pouce baissé si vous êtes contre,

**Comment by DavidDrayer** [comment]
Hello,

Présent à cette réunion, je précise ma pensée: Dans un objectif de légèreté et de simplicité (slide 85), je pense qu'il faut si possible minimiser le nombre de rôles structurels. Des rôles "prendre soin", tout comme "gardien du temps", sont des rôles qui répartissent encore plus la distribution de la tenue du cadre, mais qui potentiellement peuvent amener des zones de flous.

Je préfère donc un rôle lead qui "prend soin" de son équipe et un rôle facilitation qui "prend soin" de la qualité des réunions, que de créer un rôle supplémentaire. 
Et de le laisser en option, soit pour bien comprendre ce que veut dire "prendre soin", soit pour l'activer dans une orga qui le souhaite et/ou en a besoin.

**Comment by christophe-herault** [comment]
Je suis également de l'avis qu'il vaut mieux avoir un nombre minimal de rôles structurels pour que la mise en place pour nos clients soit la plus simple et légère possible.

**Comment by jeanlucchristin** [comment]
La proposition est validée
