### ISSUE TITLE
"Role pilotage" a la place de "role lead"

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/constitution-cellular-governance#89]
Le terme "role lead" pourrait petre remplacé par "role pilotage". 

Qu'en pensez vous ? 

Avantage : nous passons à 100% en langue française et nous distinguons plus clairement le rôle lead (cellulaire) du rôle leader pyramidal. 
Il y aurait un ROLE PILOTAGE (cellulaire) et un rôle LEADER PYRAMIDAL (pyramidal) dans le curseur managérial.

**Comment by DavidDrayer** [comment]
J'aime bien le terme de pilotage, parce que clairement ce n'est pas le pilote qui défini la direction: dans un avion, le pilote a comme tâche d'amener les passagers là où eux veulent aller. Il n'a aucune autorité de modifier la destination en cours de route, sauf éventuellement en cas d'urgence.

**Comment by jeanlucchristin** [comment]
Je me dis qu'on pourrait avoir trois mots pour gagner en clarté sur le curseur managérial. 
C'est outil est hyper puissant mais pas encore assez intuitif. 

On aurait le role pilotage dans le système cellulaire (à la place de rôle lead) ; le rôle manager pyramidal dans le système pyramidal (à la place de rôle leader pyramidal) et le leader de l'équipe constitué d'une partie du rôle lead et d'une partie du rôle manager pyramidal.

**Comment by jeanlucchristin** [comment]
Une variante bien moche mais peut être plus explicite (les attendus pilotage & pyramidal sont bicolors bleu vert) 

![image](https://user-images.githubusercontent.com/38285180/136817543-29cacbeb-5ec8-4e4a-b46d-01a9e47e56d5.png)

**Comment by jeanlucchristin** [comment]
Dans la version 2022, on part sur cette idée : 

Chaque équipe défini ce que fait son rôle pilotage à partir des redevabilités du rôle manager pyramidal et du rôle lead cellulaire. 

![image](https://user-images.githubusercontent.com/38285180/152841529-15df6cf2-2ef4-4934-a534-d90967b244a9.png)
