### ISSUE TITLE
Réunion rituelle

### ISSUE THREAD

**Issue by DavidDrayer** [jeanlucchristin/constitution-cellular-governance#91]
Proposition:

- Amener au centre du fonctionnement de la gouvernance cellulaire la réunion rituelle, appelée actuellement réunion opérationnelle ou de triage).
- Permettre à chaque équipe de construire sa réunion rituelle, c'est à dire celle qui est systématiquement planifiée à intervalle régulier.
- Fournir de quoi définir le contenu de cette réunion, sachant qu'il n'y a pas nécessairement que le circuit des demandes selon les contextes, mais qu'elles peuvent être construite avec des temps de décision collective, des temps d'échanges informels, etc...
- Proposer clairement d'ouvrir d'autres espaces spécifiques pour tout ce qui ne rentre pas dans le temps ou la structure de la réunion rituelle.
- Proposer des réunions complémentaires pré-fabriquées (sens, positionnement éthique, etc...)
- Proposer une méthode pour construire ces réunions, sous forme de briques

**Comment by jeanlucchristin** [comment]
Effectivement le fait que GC fonctionne avec des temps, plutôt qu'avec des réunions fait qu'il n'y a pas de réunion préconstruite. 
Nous avons expérimenté avec @DavidDrayer en formation à la facilitation aidée de GC le fait de faire construire des réunions rituelles ou ponctuelles sur la base d'une trame, cela a toute sa place dans la version 2022.

**Comment by jeanlucchristin** [comment]
La construction de rituels a été intégrée dans la version 2022, je peux clore cette issue.
