### ISSUE TITLE
Parler d'équipe, de cellule ou de cercle ? 

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/constitution-cellular-governance#94]
Dans un objectif de vulgarisation, j'ai envie de remplacer "cellule" par équipe. 

Nous étions passé de cercle à cellule pour rester dans le champ lexical, on se fait plaisir mais cela apporte peu aux utilisateurs et crée un nouveau concept. 

Parler de cercle a le même inconvénient. 

Dans mes accompagnements, les gens travaillent dans une ou plusieurs équipes, soit équipe opérationnelle, soit équipe projet. 
Ils ont déjà beaucoup de choses à apprendre pour passer de la culture de la performance et du blâme à la culture de l'entraide et du respect de l'autonomie. Parler d'équipe permettrait de partir de leur culture actuelle pour construire leur culture de demain. 

QU'en pensez vous ?

**Comment by DavidDrayer** [comment]
C'est pas évident. Aujourd'hui il y a les rôles et les cercles (ou cellules), dont la principale différence est celle d'avoir, pour les deuxièmes, la capacité à s'auto-organiser également en cercles et rôles, et à convoquer les réunions nécessaires.
- Comment faire la différence entre un rôle où il y a plusieurs personnes et une équipe? Il me semble que tous les deux sont des équipes...
- Si on doit déjà intégrer le terme rôle, est-il si difficile d'amener un autre terme comme cercle, alors que les représentations visuelles sont justement sous la forme de cercle?

Je trouve important de questionner ce qui est vraiment important à transmettre, de simplifier la terminologie, mais j'ai aussi peur qu'à trop vouloir coller à l'existant ça nous rende la transformation plus difficile...

**Comment by jeanlucchristin** [comment]
> C'est pas évident. Aujourd'hui il y a les rôles et les cercles (ou cellules), dont la principale différence est celle d'avoir, pour les deuxièmes, la capacité à s'auto-organiser également en cercles et rôles, et à convoquer les réunions nécessaires.
> 
> * Comment faire la différence entre un rôle où il y a plusieurs personnes et une équipe? Il me semble que tous les deux sont des équipes...
> * Si on doit déjà intégrer le terme rôle, est-il si difficile d'amener un autre terme comme cercle, alors que les représentations visuelles sont justement sous la forme de cercle?
> 
> Je trouve important de questionner ce qui est vraiment important à transmettre, de simplifier la terminologie, mais j'ai aussi peur qu'à trop vouloir coller à l'existant ça nous rende la transformation plus difficile...

Je n'ai peut-être pas la même représentation d'une équipe que toi. 
Dans les structures où j'interviens, une équipe a tout à fait "la capacité à s'auto-organiser également en cercles [équipes] et rôles, et à convoquer les réunions nécessaires." Que ce soit une équipe projet ou une équipe métier. 

Ta conclusion pose la bonne question : qu'est ce qui rendra la transformation plus facile ? 


Finalement cela nous pose la question : quelle est la différence entre un cercle et une équipe ?

**Comment by Bonzepiss** [comment]
Hi
Pourquoi? tu penses à gouvernance 'circulaire' ? ;)
Blagues à part, pour ma part le terme Cellule me va bien, je ne trouve pas
mieux pour l'instant.
Bien à toi
Olivier

Le mer. 23 juin 2021 à 09:30, jeanlucchristin ***@***.***> a
écrit :

**Comment by MarvinChambe** [comment]
Réponse pratique. Dans mon expérience récente, cellule = regroupement de personnes autour d'une raison d'être, appellation qui nous permet de savoir comment on fonctionne en interne et à qui on s'adresse. Pas de cellule "ancrage" mais une cellule "stratégique" qui regroupait tout le monde. équipe = renvoie à notre existence juridique et aussi à la manière dont on nous perçoit depuis l'extérieur. Nous sommes donc une équipe structurée en différentes cellules (la plupart d'entre nous évoluant dans beaucoup de cellules en même temps). Nous avons choisi les termes qui nous plaisaient le plus, en l'occurrence "cercles" et "stratégique", ces choix me paraissent important pour l'équipe, mais finalement ne conditionnent pas le mode de fonctionnement, la structuration de la gouvernance. Bref je ne suis pas choquée à l'idée qu'un modèle utilise son propre vocabulaire, par cohérence, pour être diffusé, compris, discuté, et qu'il soit appliqué avec une terminologie adaptée à la culture locale.

**Comment by jeanlucchristin** [comment]
Je clos cette discussion, nous maintenons pour l'instant le terme cellule qui ne semble pas créer de difficulté particulière de compréhension ou d'adhésion, et que chaque collectif peut transformer en cercle ou équipe ou quoi que ce soit au moment de l'hybridation (construction de sa propre culture de gouvernance à partir de sa culture et de ce qu'elle souhaite introduire de nouveau issu par exemple de gouvernance cellulaire).

**Comment by jeanlucchristin** [comment]
Je réouvre ce fil à la demande de l’équipe gouvernance cellulaire, Cellule Écriture, qui envisage a nouveau un changement de nom. 
@MarvinChambe

**Comment by christophe-herault** [comment]
Les équipes que j'accompagne à ce stade n'ont pas manifesté de difficulté à adopter le terme cellule. Ce terme fait sens pour eux. Je trouve qu'utiliser un vocabulaire différent du système habituel leur permet de se souvenir qu'ils ont changé de mode de gouvernance. Cela éveille leur conscience. De plus, quand on transitionne une tentreprise entière du mode pyramidale au mode cellulaire, ont peut le faire graduellement. Dans ce cas, il coexiste des équipes en mode hiérarchique, et des cellules qui appliquent la GC. Je troue donc aidant d'avoir des terminologies différentes pour ces réalités différentes.

**Comment by jeanlucchristin** [comment]
Pas d'urgence sur ce sujet, nous avons suffisamment de gros changements en cours, nous verrons cela une autre année.
