### ISSUE TITLE
tableau de bord nouvelles couleurs

### ISSUE THREAD

**Issue by jeanlucchristin** [jeanlucchristin/constitution-cellular-governance#96]
Le tableau de bord évolue peut être pour rejoindre les couleurs principales. L'efficacité humaniste version 2022 est en jaune, orange et violet. 

La question porte sur la cohérence couleurs de la page ou non. Je pense qu'on va peut-être faire quelques allé-retours pour la construire, je la colle ici.

**Comment by jeanlucchristin** [comment]
Actuel, version 2021 / 
![image](https://user-images.githubusercontent.com/38285180/146631162-fbd138d7-9c3c-44f2-9625-2430b269d42e.png)

**Comment by jeanlucchristin** [comment]
Projet version 2022. Réactions bienvenues. En particulier je me demande s'il faudrait changer les couleurs des cellules vertes vers du violet. 

![image](https://user-images.githubusercontent.com/38285180/146631194-e87c9ab5-abbc-46b5-bf6b-52acbe50b4a3.png)

**Comment by jeanlucchristin** [comment]
genre ça 

![image](https://user-images.githubusercontent.com/38285180/146632045-e5f4782f-ff3c-4076-bea8-38fccc20585e.png)

**Comment by christophe-herault** [comment]
Je vote pour la cohérence des couleurs ! Donc en ce sens, ce serait pertinent de changer la couleur verte des cellules. D'un autre côté, dans ta dernière proposition la cellule couleur bordeaux a quelque-chose de moins vivant, moins léger que le vert... Peut-être que le jaune serait plus dynamisant ?

**Comment by jeanlucchristin** [comment]
Ca prend du temps mais voici ce que ça donne : 

![image](https://user-images.githubusercontent.com/38285180/147669471-dd070cea-8b7b-48ad-acae-d0afe2aca356.png)

**Comment by jeanlucchristin** [comment]
Sujet abouti dans la V2022
