### ISSUE TITLE
Curseur managérial

### ISSUE THREAD

**Issue by christophe-herault** [jeanlucchristin/constitution-cellular-governance#97]
J'ai récemment présenté le curseur managérial à une équipe.
J'ai ressenti le besoin d'ajouter plusieurs lignes (par ex : rendre compte, réguler les tensions interpersonnelles, animer les réunions). J'ai aussi mis en gras les différences de texte entre l'organisation pyramidale et l'organisation en calage cellulaire. Et j'ai également précisé pour les activités déléguées à l'équipe si elles s'exercent en décisions collectives ou de rôle.
J'ai bien conscience que ce n'est qu'une proposition du calage cellulaire et que chaque équipe est invitée à définir ce qui est délégué et comment. Et celle liste plus précise et explicite m'aide à conduire cette discussion. C'est pour ça que je la partage ici, et que j'invite la cellule écriture à intégrer ces nouveaux éléments à la constitution dans la mesure du possible.
==> Qu'en pensez-vous ?

![image](https://user-images.githubusercontent.com/83510920/148742402-87ca99ed-b351-4533-9ce6-85f4e3258bce.png)

**Comment by jeanlucchristin** [comment]
Super job d'accompagnant bravo. 
Nous nous en inspirerons autant que possible pour l'écriture. 
Nous avons travaillé pour la version 2022, nous retrouvons l'alignement des différentes redevabilités comme dans ce tableur. 

Je trouve que le fait de répéter les 7 premières ligne est pédagogique.
Effectivement nous n'avons pas noté le "rendre compte au niveau supérieur", nous en parlerons en cellule écriture le 7 février. 
Ajuster la raison d'être des rôles c'est la même chose que organiser l'équipe, la ligne dessous. Peut être une autre rédaction à proposer pour cette ligne, mais cela doit inclure les politiques et cellules spécifiques. 

![image](https://user-images.githubusercontent.com/38285180/148784173-1b8763cf-e634-4dc9-bb42-717bf8e514d8.png)

**Comment by christophe-herault** [comment]
Bonjour à tous,
La dernière fois que j'ai présenté le curseur managérial, il m'a paru pertinent de regrouper cette liste de redevabilité selon les 3 espaces de la GC : le sens, les relations, et les contrats. Je trouve que, d'une part, cela donne de la clarté : ça permet de relier ces lignes avec ce qui est proposé dans la constitution, en particulier ça éclaire comment dans la colonne de droite les membres ses saisissent des redevabilités du manager pyramidal. Et d'autre part, cela augmente la cohérence de cet élément avec le reste de la constitution.
Seriez-vous OK pour introduire ça dans la prochaine version de la constitution ?

**Comment by jeanlucchristin** [comment]
Super idée pour l'accompagnement. 
Peut-être plus délicat dans la constitution car à vouloir tout faire apparaitre dans chaque slide on complexifie les conversations. 
Peux tu nous montrer le rendu que tu avais en inspiration ?

**Comment by jeanlucchristin** [comment]
Nous avons classé les redevabilités dans l'ordre Sens/Lien/contrat pour la version 2022. 

Merci de l'idée
