### ISSUE TITLE
Vision globale

### ISSUE THREAD

**Issue by MarvinChambe** [jeanlucchristin/constitution-cellular-governance#98]
![image](https://user-images.githubusercontent.com/87368293/173930830-10deb805-c908-49ea-a464-104a407f3c8e.png)

Commentaire issu de la séance de lecture du 15 juin 2022 : 
Diapo 10 : Vision globale (image)
Beaucoup de messages sur cette slide… une mise en image compréhensible avec un accompagnement. Quid d’une approche en solo ? Il manque une invitation à voir la slide suivante ?

Quelques détails : 
Les lignes grises à droite n’ont pas de flèches….le message peut être à préciser. Une flèche peut inviter à l’organisation d’un temps spécifique dans chaque espace.
Un mot en noir peut manqué:
 au dessus d'OPÉRATION vers METIER : “Petit pas acceptable” 
de tension vers Membre pour expliquer sa présence et voir dans quel sens il faudrait une flèche du membre vers la tension pour ce qui est de l’ordre du personnel ou de la tension vers le membre pour ce qui est de l’implication de chacun dans le traitement des tensions
Tension et Opération : “traitement”

Source : https://docs.google.com/document/d/1ZovjWQFaVdKSfTBuMBues71gxs_d-us_awlpLXODWDU/edit

**Comment by DavidDrayer** [comment]
Merci pour cette lecture.
Ce schéma est issu de la formation à la facilitation. Suite à l'incompréhension grandissante des participant-e-s vis à vis des différents éléments amenés, il a servi à recontextualiser l'ensemble des éléments précédemment étudiés. Bien sûr, il était accompagné d'une explication qui n'est pas retranscrite dans la constitution.

Il s'agit donc d'un slide ayant pour vocation d'être un support pédagogique dans la formation, et à mon avis le laisser ici sans plus de détail est plus mélangeant qu'autre chose. Soit il doit être complété par un contenu texte pédagogique, soit il doit être retiré pour intégrer un ensemble de slides servant de supports de formation, mais pas de règle.
